---
- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
    - name: start web server
      service:
        name: httpd
        state: started
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart web server
  handlers:
    - name: Restart web server
      service:
        name: httpd
        state: restarted


# - handler means for ex : copy command - code change will come only restart will work like this - so 
# write handler and copy command inside add a notify so whenever codechanges will come copy command notify 
# and notify will call handlers run the restart server tasks.